import { Sidebar } from '@/views/Sidebar'
import { SearchBar } from '@/components/global/SearchBar'
import { Metadata } from 'next'
import { ReactElement, ReactNode } from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}
const RootLayout = ({ children }: { children: ReactNode }): ReactElement => {
  return (
    <>
      <Sidebar />
      <main className='bg-red-500 border-r-4 border-black grow w-1/2'>
        {children}
      </main>
      <aside className='grow w-1/4 mx-2'>
        <SearchBar />
      </aside>
    </>
  )
}

export default RootLayout
